version: '2'

services:
  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_DATABASE=drupal
    volumes:
      - '${PWD}/mariadb:/var/lib/mysql'
      - '/var/run/mysqld'
  drupal:
    image: 'c_drupal:latest'
    links:
        - mariadb:mariadb
    environment:
      - MYSQLDB_HOST=mariadb
      - MYSQLDB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=root
      - DRUPAL_DATABASE_NAME=drupal
      - ALLOW_EMPTY_PASSWORD=yes
      - WEBROOT=/var/www/html
      - ENVIRONMENT=dev
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - '../../.:/var/www/html/'
    depends_on:
      - mariadb
    volumes_from:
      - mariadb
volumes:
  mariadb:
