#!/bin/bash

# Grab webroot
while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ $line =~ .*WEBROOT=.* ]]; then
        WT=$line
        IFS='='; WEBROOTARR=($WT); unset IFS;
        WEBROOT=${WEBROOTARR[1]}
    fi
done < "docker/dev/docker-compose.yml"
VENDOR_BIN="$WEBROOT/vendor/bin"

case "$1" in
    drupal)
        docker exec -it dev_drupal_1 "$VENDOR_BIN/$1" $2 $3
        ;;

    drush)
        docker exec -it dev_drupal_1 "$VENDOR_BIN/$1" $2 $3
        ;;

    bash)
        docker exec -it dev_drupal_1 "sh -c" $2 $3
        ;;

    *)
        echo "ANYTHING ELSE"
        ;;

esac
